/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import { TypedEventFilter, TypedEvent, TypedListener } from "./commons";

interface CreateCallInterface extends ethers.utils.Interface {
  functions: {
    "performCreate2(uint256,bytes,bytes32)": FunctionFragment;
    "performCreate(uint256,bytes)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "performCreate2",
    values: [BigNumberish, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "performCreate",
    values: [BigNumberish, BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "performCreate2",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "performCreate",
    data: BytesLike
  ): Result;

  events: {
    "ContractCreation(address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "ContractCreation"): EventFragment;
}

export class CreateCall extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: CreateCallInterface;

  functions: {
    performCreate2(
      value: BigNumberish,
      deploymentData: BytesLike,
      salt: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "performCreate2(uint256,bytes,bytes32)"(
      value: BigNumberish,
      deploymentData: BytesLike,
      salt: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    performCreate(
      value: BigNumberish,
      deploymentData: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "performCreate(uint256,bytes)"(
      value: BigNumberish,
      deploymentData: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  performCreate2(
    value: BigNumberish,
    deploymentData: BytesLike,
    salt: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "performCreate2(uint256,bytes,bytes32)"(
    value: BigNumberish,
    deploymentData: BytesLike,
    salt: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  performCreate(
    value: BigNumberish,
    deploymentData: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "performCreate(uint256,bytes)"(
    value: BigNumberish,
    deploymentData: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    performCreate2(
      value: BigNumberish,
      deploymentData: BytesLike,
      salt: BytesLike,
      overrides?: CallOverrides
    ): Promise<string>;

    "performCreate2(uint256,bytes,bytes32)"(
      value: BigNumberish,
      deploymentData: BytesLike,
      salt: BytesLike,
      overrides?: CallOverrides
    ): Promise<string>;

    performCreate(
      value: BigNumberish,
      deploymentData: BytesLike,
      overrides?: CallOverrides
    ): Promise<string>;

    "performCreate(uint256,bytes)"(
      value: BigNumberish,
      deploymentData: BytesLike,
      overrides?: CallOverrides
    ): Promise<string>;
  };

  filters: {
    ContractCreation(
      newContract: null
    ): TypedEventFilter<[string], { newContract: string }>;
  };

  estimateGas: {
    performCreate2(
      value: BigNumberish,
      deploymentData: BytesLike,
      salt: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "performCreate2(uint256,bytes,bytes32)"(
      value: BigNumberish,
      deploymentData: BytesLike,
      salt: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    performCreate(
      value: BigNumberish,
      deploymentData: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "performCreate(uint256,bytes)"(
      value: BigNumberish,
      deploymentData: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    performCreate2(
      value: BigNumberish,
      deploymentData: BytesLike,
      salt: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "performCreate2(uint256,bytes,bytes32)"(
      value: BigNumberish,
      deploymentData: BytesLike,
      salt: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    performCreate(
      value: BigNumberish,
      deploymentData: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "performCreate(uint256,bytes)"(
      value: BigNumberish,
      deploymentData: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
