/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import { TypedEventFilter, TypedEvent, TypedListener } from "./commons";

interface MockContractInterface extends ethers.utils.Interface {
  functions: {
    "MOCKS_LIST_END()": FunctionFragment;
    "MOCKS_LIST_END_HASH()": FunctionFragment;
    "MOCKS_LIST_START()": FunctionFragment;
    "SENTINEL_ANY_MOCKS()": FunctionFragment;
    "givenAnyReturn(bytes)": FunctionFragment;
    "givenAnyReturnBool(bool)": FunctionFragment;
    "givenAnyReturnUint(uint256)": FunctionFragment;
    "givenAnyReturnAddress(address)": FunctionFragment;
    "givenAnyRevert()": FunctionFragment;
    "givenAnyRevertWithMessage(string)": FunctionFragment;
    "givenAnyRunOutOfGas()": FunctionFragment;
    "givenCalldataReturn(bytes,bytes)": FunctionFragment;
    "givenCalldataReturnBool(bytes,bool)": FunctionFragment;
    "givenCalldataReturnUint(bytes,uint256)": FunctionFragment;
    "givenCalldataReturnAddress(bytes,address)": FunctionFragment;
    "givenMethodReturn(bytes,bytes)": FunctionFragment;
    "givenMethodReturnBool(bytes,bool)": FunctionFragment;
    "givenMethodReturnUint(bytes,uint256)": FunctionFragment;
    "givenMethodReturnAddress(bytes,address)": FunctionFragment;
    "givenCalldataRevert(bytes)": FunctionFragment;
    "givenMethodRevert(bytes)": FunctionFragment;
    "givenCalldataRevertWithMessage(bytes,string)": FunctionFragment;
    "givenMethodRevertWithMessage(bytes,string)": FunctionFragment;
    "givenCalldataRunOutOfGas(bytes)": FunctionFragment;
    "givenMethodRunOutOfGas(bytes)": FunctionFragment;
    "invocationCount()": FunctionFragment;
    "invocationCountForMethod(bytes)": FunctionFragment;
    "invocationCountForCalldata(bytes)": FunctionFragment;
    "reset()": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "MOCKS_LIST_END",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MOCKS_LIST_END_HASH",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MOCKS_LIST_START",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "SENTINEL_ANY_MOCKS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "givenAnyReturn",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "givenAnyReturnBool",
    values: [boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "givenAnyReturnUint",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "givenAnyReturnAddress",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "givenAnyRevert",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "givenAnyRevertWithMessage",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "givenAnyRunOutOfGas",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "givenCalldataReturn",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "givenCalldataReturnBool",
    values: [BytesLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "givenCalldataReturnUint",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "givenCalldataReturnAddress",
    values: [BytesLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "givenMethodReturn",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "givenMethodReturnBool",
    values: [BytesLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "givenMethodReturnUint",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "givenMethodReturnAddress",
    values: [BytesLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "givenCalldataRevert",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "givenMethodRevert",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "givenCalldataRevertWithMessage",
    values: [BytesLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "givenMethodRevertWithMessage",
    values: [BytesLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "givenCalldataRunOutOfGas",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "givenMethodRunOutOfGas",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "invocationCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "invocationCountForMethod",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "invocationCountForCalldata",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "reset", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "MOCKS_LIST_END",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MOCKS_LIST_END_HASH",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MOCKS_LIST_START",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "SENTINEL_ANY_MOCKS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "givenAnyReturn",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "givenAnyReturnBool",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "givenAnyReturnUint",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "givenAnyReturnAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "givenAnyRevert",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "givenAnyRevertWithMessage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "givenAnyRunOutOfGas",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "givenCalldataReturn",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "givenCalldataReturnBool",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "givenCalldataReturnUint",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "givenCalldataReturnAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "givenMethodReturn",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "givenMethodReturnBool",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "givenMethodReturnUint",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "givenMethodReturnAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "givenCalldataRevert",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "givenMethodRevert",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "givenCalldataRevertWithMessage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "givenMethodRevertWithMessage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "givenCalldataRunOutOfGas",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "givenMethodRunOutOfGas",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "invocationCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "invocationCountForMethod",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "invocationCountForCalldata",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "reset", data: BytesLike): Result;

  events: {};
}

export class MockContract extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: MockContractInterface;

  functions: {
    MOCKS_LIST_END(overrides?: CallOverrides): Promise<[string]>;

    "MOCKS_LIST_END()"(overrides?: CallOverrides): Promise<[string]>;

    MOCKS_LIST_END_HASH(overrides?: CallOverrides): Promise<[string]>;

    "MOCKS_LIST_END_HASH()"(overrides?: CallOverrides): Promise<[string]>;

    MOCKS_LIST_START(overrides?: CallOverrides): Promise<[string]>;

    "MOCKS_LIST_START()"(overrides?: CallOverrides): Promise<[string]>;

    SENTINEL_ANY_MOCKS(overrides?: CallOverrides): Promise<[string]>;

    "SENTINEL_ANY_MOCKS()"(overrides?: CallOverrides): Promise<[string]>;

    givenAnyReturn(
      response: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "givenAnyReturn(bytes)"(
      response: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    givenAnyReturnBool(
      response: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "givenAnyReturnBool(bool)"(
      response: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    givenAnyReturnUint(
      response: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "givenAnyReturnUint(uint256)"(
      response: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    givenAnyReturnAddress(
      response: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "givenAnyReturnAddress(address)"(
      response: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    givenAnyRevert(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "givenAnyRevert()"(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    givenAnyRevertWithMessage(
      message: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "givenAnyRevertWithMessage(string)"(
      message: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    givenAnyRunOutOfGas(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "givenAnyRunOutOfGas()"(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    givenCalldataReturn(
      call: BytesLike,
      response: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "givenCalldataReturn(bytes,bytes)"(
      call: BytesLike,
      response: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    givenCalldataReturnBool(
      call: BytesLike,
      response: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "givenCalldataReturnBool(bytes,bool)"(
      call: BytesLike,
      response: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    givenCalldataReturnUint(
      call: BytesLike,
      response: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "givenCalldataReturnUint(bytes,uint256)"(
      call: BytesLike,
      response: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    givenCalldataReturnAddress(
      call: BytesLike,
      response: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "givenCalldataReturnAddress(bytes,address)"(
      call: BytesLike,
      response: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    givenMethodReturn(
      call: BytesLike,
      response: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "givenMethodReturn(bytes,bytes)"(
      call: BytesLike,
      response: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    givenMethodReturnBool(
      call: BytesLike,
      response: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "givenMethodReturnBool(bytes,bool)"(
      call: BytesLike,
      response: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    givenMethodReturnUint(
      call: BytesLike,
      response: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "givenMethodReturnUint(bytes,uint256)"(
      call: BytesLike,
      response: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    givenMethodReturnAddress(
      call: BytesLike,
      response: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "givenMethodReturnAddress(bytes,address)"(
      call: BytesLike,
      response: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    givenCalldataRevert(
      call: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "givenCalldataRevert(bytes)"(
      call: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    givenMethodRevert(
      call: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "givenMethodRevert(bytes)"(
      call: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    givenCalldataRevertWithMessage(
      call: BytesLike,
      message: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "givenCalldataRevertWithMessage(bytes,string)"(
      call: BytesLike,
      message: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    givenMethodRevertWithMessage(
      call: BytesLike,
      message: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "givenMethodRevertWithMessage(bytes,string)"(
      call: BytesLike,
      message: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    givenCalldataRunOutOfGas(
      call: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "givenCalldataRunOutOfGas(bytes)"(
      call: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    givenMethodRunOutOfGas(
      call: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "givenMethodRunOutOfGas(bytes)"(
      call: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    invocationCount(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "invocationCount()"(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    invocationCountForMethod(
      call: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "invocationCountForMethod(bytes)"(
      call: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    invocationCountForCalldata(
      call: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "invocationCountForCalldata(bytes)"(
      call: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    reset(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "reset()"(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  MOCKS_LIST_END(overrides?: CallOverrides): Promise<string>;

  "MOCKS_LIST_END()"(overrides?: CallOverrides): Promise<string>;

  MOCKS_LIST_END_HASH(overrides?: CallOverrides): Promise<string>;

  "MOCKS_LIST_END_HASH()"(overrides?: CallOverrides): Promise<string>;

  MOCKS_LIST_START(overrides?: CallOverrides): Promise<string>;

  "MOCKS_LIST_START()"(overrides?: CallOverrides): Promise<string>;

  SENTINEL_ANY_MOCKS(overrides?: CallOverrides): Promise<string>;

  "SENTINEL_ANY_MOCKS()"(overrides?: CallOverrides): Promise<string>;

  givenAnyReturn(
    response: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "givenAnyReturn(bytes)"(
    response: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  givenAnyReturnBool(
    response: boolean,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "givenAnyReturnBool(bool)"(
    response: boolean,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  givenAnyReturnUint(
    response: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "givenAnyReturnUint(uint256)"(
    response: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  givenAnyReturnAddress(
    response: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "givenAnyReturnAddress(address)"(
    response: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  givenAnyRevert(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "givenAnyRevert()"(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  givenAnyRevertWithMessage(
    message: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "givenAnyRevertWithMessage(string)"(
    message: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  givenAnyRunOutOfGas(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "givenAnyRunOutOfGas()"(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  givenCalldataReturn(
    call: BytesLike,
    response: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "givenCalldataReturn(bytes,bytes)"(
    call: BytesLike,
    response: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  givenCalldataReturnBool(
    call: BytesLike,
    response: boolean,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "givenCalldataReturnBool(bytes,bool)"(
    call: BytesLike,
    response: boolean,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  givenCalldataReturnUint(
    call: BytesLike,
    response: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "givenCalldataReturnUint(bytes,uint256)"(
    call: BytesLike,
    response: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  givenCalldataReturnAddress(
    call: BytesLike,
    response: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "givenCalldataReturnAddress(bytes,address)"(
    call: BytesLike,
    response: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  givenMethodReturn(
    call: BytesLike,
    response: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "givenMethodReturn(bytes,bytes)"(
    call: BytesLike,
    response: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  givenMethodReturnBool(
    call: BytesLike,
    response: boolean,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "givenMethodReturnBool(bytes,bool)"(
    call: BytesLike,
    response: boolean,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  givenMethodReturnUint(
    call: BytesLike,
    response: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "givenMethodReturnUint(bytes,uint256)"(
    call: BytesLike,
    response: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  givenMethodReturnAddress(
    call: BytesLike,
    response: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "givenMethodReturnAddress(bytes,address)"(
    call: BytesLike,
    response: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  givenCalldataRevert(
    call: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "givenCalldataRevert(bytes)"(
    call: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  givenMethodRevert(
    call: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "givenMethodRevert(bytes)"(
    call: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  givenCalldataRevertWithMessage(
    call: BytesLike,
    message: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "givenCalldataRevertWithMessage(bytes,string)"(
    call: BytesLike,
    message: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  givenMethodRevertWithMessage(
    call: BytesLike,
    message: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "givenMethodRevertWithMessage(bytes,string)"(
    call: BytesLike,
    message: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  givenCalldataRunOutOfGas(
    call: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "givenCalldataRunOutOfGas(bytes)"(
    call: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  givenMethodRunOutOfGas(
    call: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "givenMethodRunOutOfGas(bytes)"(
    call: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  invocationCount(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "invocationCount()"(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  invocationCountForMethod(
    call: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "invocationCountForMethod(bytes)"(
    call: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  invocationCountForCalldata(
    call: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "invocationCountForCalldata(bytes)"(
    call: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  reset(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "reset()"(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    MOCKS_LIST_END(overrides?: CallOverrides): Promise<string>;

    "MOCKS_LIST_END()"(overrides?: CallOverrides): Promise<string>;

    MOCKS_LIST_END_HASH(overrides?: CallOverrides): Promise<string>;

    "MOCKS_LIST_END_HASH()"(overrides?: CallOverrides): Promise<string>;

    MOCKS_LIST_START(overrides?: CallOverrides): Promise<string>;

    "MOCKS_LIST_START()"(overrides?: CallOverrides): Promise<string>;

    SENTINEL_ANY_MOCKS(overrides?: CallOverrides): Promise<string>;

    "SENTINEL_ANY_MOCKS()"(overrides?: CallOverrides): Promise<string>;

    givenAnyReturn(
      response: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    "givenAnyReturn(bytes)"(
      response: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    givenAnyReturnBool(
      response: boolean,
      overrides?: CallOverrides
    ): Promise<void>;

    "givenAnyReturnBool(bool)"(
      response: boolean,
      overrides?: CallOverrides
    ): Promise<void>;

    givenAnyReturnUint(
      response: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "givenAnyReturnUint(uint256)"(
      response: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    givenAnyReturnAddress(
      response: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "givenAnyReturnAddress(address)"(
      response: string,
      overrides?: CallOverrides
    ): Promise<void>;

    givenAnyRevert(overrides?: CallOverrides): Promise<void>;

    "givenAnyRevert()"(overrides?: CallOverrides): Promise<void>;

    givenAnyRevertWithMessage(
      message: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "givenAnyRevertWithMessage(string)"(
      message: string,
      overrides?: CallOverrides
    ): Promise<void>;

    givenAnyRunOutOfGas(overrides?: CallOverrides): Promise<void>;

    "givenAnyRunOutOfGas()"(overrides?: CallOverrides): Promise<void>;

    givenCalldataReturn(
      call: BytesLike,
      response: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    "givenCalldataReturn(bytes,bytes)"(
      call: BytesLike,
      response: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    givenCalldataReturnBool(
      call: BytesLike,
      response: boolean,
      overrides?: CallOverrides
    ): Promise<void>;

    "givenCalldataReturnBool(bytes,bool)"(
      call: BytesLike,
      response: boolean,
      overrides?: CallOverrides
    ): Promise<void>;

    givenCalldataReturnUint(
      call: BytesLike,
      response: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "givenCalldataReturnUint(bytes,uint256)"(
      call: BytesLike,
      response: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    givenCalldataReturnAddress(
      call: BytesLike,
      response: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "givenCalldataReturnAddress(bytes,address)"(
      call: BytesLike,
      response: string,
      overrides?: CallOverrides
    ): Promise<void>;

    givenMethodReturn(
      call: BytesLike,
      response: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    "givenMethodReturn(bytes,bytes)"(
      call: BytesLike,
      response: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    givenMethodReturnBool(
      call: BytesLike,
      response: boolean,
      overrides?: CallOverrides
    ): Promise<void>;

    "givenMethodReturnBool(bytes,bool)"(
      call: BytesLike,
      response: boolean,
      overrides?: CallOverrides
    ): Promise<void>;

    givenMethodReturnUint(
      call: BytesLike,
      response: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "givenMethodReturnUint(bytes,uint256)"(
      call: BytesLike,
      response: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    givenMethodReturnAddress(
      call: BytesLike,
      response: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "givenMethodReturnAddress(bytes,address)"(
      call: BytesLike,
      response: string,
      overrides?: CallOverrides
    ): Promise<void>;

    givenCalldataRevert(
      call: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    "givenCalldataRevert(bytes)"(
      call: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    givenMethodRevert(
      call: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    "givenMethodRevert(bytes)"(
      call: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    givenCalldataRevertWithMessage(
      call: BytesLike,
      message: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "givenCalldataRevertWithMessage(bytes,string)"(
      call: BytesLike,
      message: string,
      overrides?: CallOverrides
    ): Promise<void>;

    givenMethodRevertWithMessage(
      call: BytesLike,
      message: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "givenMethodRevertWithMessage(bytes,string)"(
      call: BytesLike,
      message: string,
      overrides?: CallOverrides
    ): Promise<void>;

    givenCalldataRunOutOfGas(
      call: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    "givenCalldataRunOutOfGas(bytes)"(
      call: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    givenMethodRunOutOfGas(
      call: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    "givenMethodRunOutOfGas(bytes)"(
      call: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    invocationCount(overrides?: CallOverrides): Promise<BigNumber>;

    "invocationCount()"(overrides?: CallOverrides): Promise<BigNumber>;

    invocationCountForMethod(
      call: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "invocationCountForMethod(bytes)"(
      call: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    invocationCountForCalldata(
      call: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "invocationCountForCalldata(bytes)"(
      call: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    reset(overrides?: CallOverrides): Promise<void>;

    "reset()"(overrides?: CallOverrides): Promise<void>;
  };

  filters: {};

  estimateGas: {
    MOCKS_LIST_END(overrides?: CallOverrides): Promise<BigNumber>;

    "MOCKS_LIST_END()"(overrides?: CallOverrides): Promise<BigNumber>;

    MOCKS_LIST_END_HASH(overrides?: CallOverrides): Promise<BigNumber>;

    "MOCKS_LIST_END_HASH()"(overrides?: CallOverrides): Promise<BigNumber>;

    MOCKS_LIST_START(overrides?: CallOverrides): Promise<BigNumber>;

    "MOCKS_LIST_START()"(overrides?: CallOverrides): Promise<BigNumber>;

    SENTINEL_ANY_MOCKS(overrides?: CallOverrides): Promise<BigNumber>;

    "SENTINEL_ANY_MOCKS()"(overrides?: CallOverrides): Promise<BigNumber>;

    givenAnyReturn(
      response: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "givenAnyReturn(bytes)"(
      response: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    givenAnyReturnBool(
      response: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "givenAnyReturnBool(bool)"(
      response: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    givenAnyReturnUint(
      response: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "givenAnyReturnUint(uint256)"(
      response: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    givenAnyReturnAddress(
      response: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "givenAnyReturnAddress(address)"(
      response: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    givenAnyRevert(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "givenAnyRevert()"(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    givenAnyRevertWithMessage(
      message: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "givenAnyRevertWithMessage(string)"(
      message: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    givenAnyRunOutOfGas(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "givenAnyRunOutOfGas()"(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    givenCalldataReturn(
      call: BytesLike,
      response: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "givenCalldataReturn(bytes,bytes)"(
      call: BytesLike,
      response: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    givenCalldataReturnBool(
      call: BytesLike,
      response: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "givenCalldataReturnBool(bytes,bool)"(
      call: BytesLike,
      response: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    givenCalldataReturnUint(
      call: BytesLike,
      response: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "givenCalldataReturnUint(bytes,uint256)"(
      call: BytesLike,
      response: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    givenCalldataReturnAddress(
      call: BytesLike,
      response: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "givenCalldataReturnAddress(bytes,address)"(
      call: BytesLike,
      response: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    givenMethodReturn(
      call: BytesLike,
      response: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "givenMethodReturn(bytes,bytes)"(
      call: BytesLike,
      response: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    givenMethodReturnBool(
      call: BytesLike,
      response: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "givenMethodReturnBool(bytes,bool)"(
      call: BytesLike,
      response: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    givenMethodReturnUint(
      call: BytesLike,
      response: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "givenMethodReturnUint(bytes,uint256)"(
      call: BytesLike,
      response: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    givenMethodReturnAddress(
      call: BytesLike,
      response: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "givenMethodReturnAddress(bytes,address)"(
      call: BytesLike,
      response: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    givenCalldataRevert(
      call: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "givenCalldataRevert(bytes)"(
      call: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    givenMethodRevert(
      call: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "givenMethodRevert(bytes)"(
      call: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    givenCalldataRevertWithMessage(
      call: BytesLike,
      message: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "givenCalldataRevertWithMessage(bytes,string)"(
      call: BytesLike,
      message: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    givenMethodRevertWithMessage(
      call: BytesLike,
      message: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "givenMethodRevertWithMessage(bytes,string)"(
      call: BytesLike,
      message: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    givenCalldataRunOutOfGas(
      call: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "givenCalldataRunOutOfGas(bytes)"(
      call: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    givenMethodRunOutOfGas(
      call: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "givenMethodRunOutOfGas(bytes)"(
      call: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    invocationCount(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "invocationCount()"(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    invocationCountForMethod(
      call: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "invocationCountForMethod(bytes)"(
      call: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    invocationCountForCalldata(
      call: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "invocationCountForCalldata(bytes)"(
      call: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    reset(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "reset()"(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    MOCKS_LIST_END(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "MOCKS_LIST_END()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    MOCKS_LIST_END_HASH(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "MOCKS_LIST_END_HASH()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    MOCKS_LIST_START(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "MOCKS_LIST_START()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    SENTINEL_ANY_MOCKS(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "SENTINEL_ANY_MOCKS()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    givenAnyReturn(
      response: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "givenAnyReturn(bytes)"(
      response: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    givenAnyReturnBool(
      response: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "givenAnyReturnBool(bool)"(
      response: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    givenAnyReturnUint(
      response: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "givenAnyReturnUint(uint256)"(
      response: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    givenAnyReturnAddress(
      response: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "givenAnyReturnAddress(address)"(
      response: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    givenAnyRevert(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "givenAnyRevert()"(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    givenAnyRevertWithMessage(
      message: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "givenAnyRevertWithMessage(string)"(
      message: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    givenAnyRunOutOfGas(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "givenAnyRunOutOfGas()"(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    givenCalldataReturn(
      call: BytesLike,
      response: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "givenCalldataReturn(bytes,bytes)"(
      call: BytesLike,
      response: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    givenCalldataReturnBool(
      call: BytesLike,
      response: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "givenCalldataReturnBool(bytes,bool)"(
      call: BytesLike,
      response: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    givenCalldataReturnUint(
      call: BytesLike,
      response: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "givenCalldataReturnUint(bytes,uint256)"(
      call: BytesLike,
      response: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    givenCalldataReturnAddress(
      call: BytesLike,
      response: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "givenCalldataReturnAddress(bytes,address)"(
      call: BytesLike,
      response: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    givenMethodReturn(
      call: BytesLike,
      response: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "givenMethodReturn(bytes,bytes)"(
      call: BytesLike,
      response: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    givenMethodReturnBool(
      call: BytesLike,
      response: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "givenMethodReturnBool(bytes,bool)"(
      call: BytesLike,
      response: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    givenMethodReturnUint(
      call: BytesLike,
      response: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "givenMethodReturnUint(bytes,uint256)"(
      call: BytesLike,
      response: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    givenMethodReturnAddress(
      call: BytesLike,
      response: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "givenMethodReturnAddress(bytes,address)"(
      call: BytesLike,
      response: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    givenCalldataRevert(
      call: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "givenCalldataRevert(bytes)"(
      call: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    givenMethodRevert(
      call: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "givenMethodRevert(bytes)"(
      call: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    givenCalldataRevertWithMessage(
      call: BytesLike,
      message: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "givenCalldataRevertWithMessage(bytes,string)"(
      call: BytesLike,
      message: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    givenMethodRevertWithMessage(
      call: BytesLike,
      message: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "givenMethodRevertWithMessage(bytes,string)"(
      call: BytesLike,
      message: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    givenCalldataRunOutOfGas(
      call: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "givenCalldataRunOutOfGas(bytes)"(
      call: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    givenMethodRunOutOfGas(
      call: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "givenMethodRunOutOfGas(bytes)"(
      call: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    invocationCount(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "invocationCount()"(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    invocationCountForMethod(
      call: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "invocationCountForMethod(bytes)"(
      call: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    invocationCountForCalldata(
      call: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "invocationCountForCalldata(bytes)"(
      call: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    reset(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "reset()"(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
