/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import { TypedEventFilter, TypedEvent, TypedListener } from "./commons";

interface SocialRecoveryModuleInterface extends ethers.utils.Interface {
  functions: {
    "NAME()": FunctionFragment;
    "VERSION()": FunctionFragment;
    "changeMasterCopy(address)": FunctionFragment;
    "friends(uint256)": FunctionFragment;
    "isConfirmed(bytes32,address)": FunctionFragment;
    "isExecuted(bytes32)": FunctionFragment;
    "isFriend(address)": FunctionFragment;
    "manager()": FunctionFragment;
    "threshold()": FunctionFragment;
    "setup(address[],uint256)": FunctionFragment;
    "confirmTransaction(bytes32)": FunctionFragment;
    "recoverAccess(address,address,address)": FunctionFragment;
    "isConfirmedByRequiredFriends(bytes32)": FunctionFragment;
    "getDataHash(bytes)": FunctionFragment;
  };

  encodeFunctionData(functionFragment: "NAME", values?: undefined): string;
  encodeFunctionData(functionFragment: "VERSION", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "changeMasterCopy",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "friends",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "isConfirmed",
    values: [BytesLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "isExecuted",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "isFriend", values: [string]): string;
  encodeFunctionData(functionFragment: "manager", values?: undefined): string;
  encodeFunctionData(functionFragment: "threshold", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "setup",
    values: [string[], BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "confirmTransaction",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "recoverAccess",
    values: [string, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "isConfirmedByRequiredFriends",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getDataHash",
    values: [BytesLike]
  ): string;

  decodeFunctionResult(functionFragment: "NAME", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "VERSION", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "changeMasterCopy",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "friends", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isConfirmed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isExecuted", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "isFriend", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "manager", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "threshold", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setup", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "confirmTransaction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "recoverAccess",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isConfirmedByRequiredFriends",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getDataHash",
    data: BytesLike
  ): Result;

  events: {
    "ChangedMasterCopy(address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "ChangedMasterCopy"): EventFragment;
}

export class SocialRecoveryModule extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: SocialRecoveryModuleInterface;

  functions: {
    NAME(overrides?: CallOverrides): Promise<[string]>;

    "NAME()"(overrides?: CallOverrides): Promise<[string]>;

    VERSION(overrides?: CallOverrides): Promise<[string]>;

    "VERSION()"(overrides?: CallOverrides): Promise<[string]>;

    /**
     * Allows to upgrade the contract. This can only be done via a Safe transaction.
     * @param _masterCopy New contract address.
     */
    changeMasterCopy(
      _masterCopy: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    /**
     * Allows to upgrade the contract. This can only be done via a Safe transaction.
     * @param _masterCopy New contract address.
     */
    "changeMasterCopy(address)"(
      _masterCopy: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    friends(arg0: BigNumberish, overrides?: CallOverrides): Promise<[string]>;

    "friends(uint256)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string]>;

    isConfirmed(
      arg0: BytesLike,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    "isConfirmed(bytes32,address)"(
      arg0: BytesLike,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    isExecuted(arg0: BytesLike, overrides?: CallOverrides): Promise<[boolean]>;

    "isExecuted(bytes32)"(
      arg0: BytesLike,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    isFriend(arg0: string, overrides?: CallOverrides): Promise<[boolean]>;

    "isFriend(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    manager(overrides?: CallOverrides): Promise<[string]>;

    "manager()"(overrides?: CallOverrides): Promise<[string]>;

    threshold(overrides?: CallOverrides): Promise<[BigNumber]>;

    "threshold()"(overrides?: CallOverrides): Promise<[BigNumber]>;

    /**
     * Setup function sets initial storage of contract.
     * @param _friends List of friends' addresses.
     * @param _threshold Required number of friends to confirm replacement.
     */
    setup(
      _friends: string[],
      _threshold: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    /**
     * Setup function sets initial storage of contract.
     * @param _friends List of friends' addresses.
     * @param _threshold Required number of friends to confirm replacement.
     */
    "setup(address[],uint256)"(
      _friends: string[],
      _threshold: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    /**
     * Allows a friend to confirm a Safe transaction.
     * @param dataHash Safe transaction hash.
     */
    confirmTransaction(
      dataHash: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    /**
     * Allows a friend to confirm a Safe transaction.
     * @param dataHash Safe transaction hash.
     */
    "confirmTransaction(bytes32)"(
      dataHash: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    /**
     * Returns if Safe transaction is a valid owner replacement transaction.
     * @param newOwner New owner address.
     * @param oldOwner Owner address to be replaced.
     * @param prevOwner Owner that pointed to the owner to be replaced in the linked list
     * @returns Returns if transaction can be executed.
     */
    recoverAccess(
      prevOwner: string,
      oldOwner: string,
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    /**
     * Returns if Safe transaction is a valid owner replacement transaction.
     * @param newOwner New owner address.
     * @param oldOwner Owner address to be replaced.
     * @param prevOwner Owner that pointed to the owner to be replaced in the linked list
     * @returns Returns if transaction can be executed.
     */
    "recoverAccess(address,address,address)"(
      prevOwner: string,
      oldOwner: string,
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    /**
     * Returns if Safe transaction is a valid owner replacement transaction.
     * @param dataHash Data hash.
     * @returns Confirmation status.
     */
    isConfirmedByRequiredFriends(
      dataHash: BytesLike,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    /**
     * Returns if Safe transaction is a valid owner replacement transaction.
     * @param dataHash Data hash.
     * @returns Confirmation status.
     */
    "isConfirmedByRequiredFriends(bytes32)"(
      dataHash: BytesLike,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    /**
     * Returns hash of data encoding owner replacement.
     * @param data Data payload.
     * @returns Data hash.
     */
    getDataHash(data: BytesLike, overrides?: CallOverrides): Promise<[string]>;

    /**
     * Returns hash of data encoding owner replacement.
     * @param data Data payload.
     * @returns Data hash.
     */
    "getDataHash(bytes)"(
      data: BytesLike,
      overrides?: CallOverrides
    ): Promise<[string]>;
  };

  NAME(overrides?: CallOverrides): Promise<string>;

  "NAME()"(overrides?: CallOverrides): Promise<string>;

  VERSION(overrides?: CallOverrides): Promise<string>;

  "VERSION()"(overrides?: CallOverrides): Promise<string>;

  /**
   * Allows to upgrade the contract. This can only be done via a Safe transaction.
   * @param _masterCopy New contract address.
   */
  changeMasterCopy(
    _masterCopy: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  /**
   * Allows to upgrade the contract. This can only be done via a Safe transaction.
   * @param _masterCopy New contract address.
   */
  "changeMasterCopy(address)"(
    _masterCopy: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  friends(arg0: BigNumberish, overrides?: CallOverrides): Promise<string>;

  "friends(uint256)"(
    arg0: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  isConfirmed(
    arg0: BytesLike,
    arg1: string,
    overrides?: CallOverrides
  ): Promise<boolean>;

  "isConfirmed(bytes32,address)"(
    arg0: BytesLike,
    arg1: string,
    overrides?: CallOverrides
  ): Promise<boolean>;

  isExecuted(arg0: BytesLike, overrides?: CallOverrides): Promise<boolean>;

  "isExecuted(bytes32)"(
    arg0: BytesLike,
    overrides?: CallOverrides
  ): Promise<boolean>;

  isFriend(arg0: string, overrides?: CallOverrides): Promise<boolean>;

  "isFriend(address)"(
    arg0: string,
    overrides?: CallOverrides
  ): Promise<boolean>;

  manager(overrides?: CallOverrides): Promise<string>;

  "manager()"(overrides?: CallOverrides): Promise<string>;

  threshold(overrides?: CallOverrides): Promise<BigNumber>;

  "threshold()"(overrides?: CallOverrides): Promise<BigNumber>;

  /**
   * Setup function sets initial storage of contract.
   * @param _friends List of friends' addresses.
   * @param _threshold Required number of friends to confirm replacement.
   */
  setup(
    _friends: string[],
    _threshold: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  /**
   * Setup function sets initial storage of contract.
   * @param _friends List of friends' addresses.
   * @param _threshold Required number of friends to confirm replacement.
   */
  "setup(address[],uint256)"(
    _friends: string[],
    _threshold: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  /**
   * Allows a friend to confirm a Safe transaction.
   * @param dataHash Safe transaction hash.
   */
  confirmTransaction(
    dataHash: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  /**
   * Allows a friend to confirm a Safe transaction.
   * @param dataHash Safe transaction hash.
   */
  "confirmTransaction(bytes32)"(
    dataHash: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  /**
   * Returns if Safe transaction is a valid owner replacement transaction.
   * @param newOwner New owner address.
   * @param oldOwner Owner address to be replaced.
   * @param prevOwner Owner that pointed to the owner to be replaced in the linked list
   * @returns Returns if transaction can be executed.
   */
  recoverAccess(
    prevOwner: string,
    oldOwner: string,
    newOwner: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  /**
   * Returns if Safe transaction is a valid owner replacement transaction.
   * @param newOwner New owner address.
   * @param oldOwner Owner address to be replaced.
   * @param prevOwner Owner that pointed to the owner to be replaced in the linked list
   * @returns Returns if transaction can be executed.
   */
  "recoverAccess(address,address,address)"(
    prevOwner: string,
    oldOwner: string,
    newOwner: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  /**
   * Returns if Safe transaction is a valid owner replacement transaction.
   * @param dataHash Data hash.
   * @returns Confirmation status.
   */
  isConfirmedByRequiredFriends(
    dataHash: BytesLike,
    overrides?: CallOverrides
  ): Promise<boolean>;

  /**
   * Returns if Safe transaction is a valid owner replacement transaction.
   * @param dataHash Data hash.
   * @returns Confirmation status.
   */
  "isConfirmedByRequiredFriends(bytes32)"(
    dataHash: BytesLike,
    overrides?: CallOverrides
  ): Promise<boolean>;

  /**
   * Returns hash of data encoding owner replacement.
   * @param data Data payload.
   * @returns Data hash.
   */
  getDataHash(data: BytesLike, overrides?: CallOverrides): Promise<string>;

  /**
   * Returns hash of data encoding owner replacement.
   * @param data Data payload.
   * @returns Data hash.
   */
  "getDataHash(bytes)"(
    data: BytesLike,
    overrides?: CallOverrides
  ): Promise<string>;

  callStatic: {
    NAME(overrides?: CallOverrides): Promise<string>;

    "NAME()"(overrides?: CallOverrides): Promise<string>;

    VERSION(overrides?: CallOverrides): Promise<string>;

    "VERSION()"(overrides?: CallOverrides): Promise<string>;

    /**
     * Allows to upgrade the contract. This can only be done via a Safe transaction.
     * @param _masterCopy New contract address.
     */
    changeMasterCopy(
      _masterCopy: string,
      overrides?: CallOverrides
    ): Promise<void>;

    /**
     * Allows to upgrade the contract. This can only be done via a Safe transaction.
     * @param _masterCopy New contract address.
     */
    "changeMasterCopy(address)"(
      _masterCopy: string,
      overrides?: CallOverrides
    ): Promise<void>;

    friends(arg0: BigNumberish, overrides?: CallOverrides): Promise<string>;

    "friends(uint256)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    isConfirmed(
      arg0: BytesLike,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    "isConfirmed(bytes32,address)"(
      arg0: BytesLike,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    isExecuted(arg0: BytesLike, overrides?: CallOverrides): Promise<boolean>;

    "isExecuted(bytes32)"(
      arg0: BytesLike,
      overrides?: CallOverrides
    ): Promise<boolean>;

    isFriend(arg0: string, overrides?: CallOverrides): Promise<boolean>;

    "isFriend(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    manager(overrides?: CallOverrides): Promise<string>;

    "manager()"(overrides?: CallOverrides): Promise<string>;

    threshold(overrides?: CallOverrides): Promise<BigNumber>;

    "threshold()"(overrides?: CallOverrides): Promise<BigNumber>;

    /**
     * Setup function sets initial storage of contract.
     * @param _friends List of friends' addresses.
     * @param _threshold Required number of friends to confirm replacement.
     */
    setup(
      _friends: string[],
      _threshold: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    /**
     * Setup function sets initial storage of contract.
     * @param _friends List of friends' addresses.
     * @param _threshold Required number of friends to confirm replacement.
     */
    "setup(address[],uint256)"(
      _friends: string[],
      _threshold: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    /**
     * Allows a friend to confirm a Safe transaction.
     * @param dataHash Safe transaction hash.
     */
    confirmTransaction(
      dataHash: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    /**
     * Allows a friend to confirm a Safe transaction.
     * @param dataHash Safe transaction hash.
     */
    "confirmTransaction(bytes32)"(
      dataHash: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    /**
     * Returns if Safe transaction is a valid owner replacement transaction.
     * @param newOwner New owner address.
     * @param oldOwner Owner address to be replaced.
     * @param prevOwner Owner that pointed to the owner to be replaced in the linked list
     * @returns Returns if transaction can be executed.
     */
    recoverAccess(
      prevOwner: string,
      oldOwner: string,
      newOwner: string,
      overrides?: CallOverrides
    ): Promise<void>;

    /**
     * Returns if Safe transaction is a valid owner replacement transaction.
     * @param newOwner New owner address.
     * @param oldOwner Owner address to be replaced.
     * @param prevOwner Owner that pointed to the owner to be replaced in the linked list
     * @returns Returns if transaction can be executed.
     */
    "recoverAccess(address,address,address)"(
      prevOwner: string,
      oldOwner: string,
      newOwner: string,
      overrides?: CallOverrides
    ): Promise<void>;

    /**
     * Returns if Safe transaction is a valid owner replacement transaction.
     * @param dataHash Data hash.
     * @returns Confirmation status.
     */
    isConfirmedByRequiredFriends(
      dataHash: BytesLike,
      overrides?: CallOverrides
    ): Promise<boolean>;

    /**
     * Returns if Safe transaction is a valid owner replacement transaction.
     * @param dataHash Data hash.
     * @returns Confirmation status.
     */
    "isConfirmedByRequiredFriends(bytes32)"(
      dataHash: BytesLike,
      overrides?: CallOverrides
    ): Promise<boolean>;

    /**
     * Returns hash of data encoding owner replacement.
     * @param data Data payload.
     * @returns Data hash.
     */
    getDataHash(data: BytesLike, overrides?: CallOverrides): Promise<string>;

    /**
     * Returns hash of data encoding owner replacement.
     * @param data Data payload.
     * @returns Data hash.
     */
    "getDataHash(bytes)"(
      data: BytesLike,
      overrides?: CallOverrides
    ): Promise<string>;
  };

  filters: {
    ChangedMasterCopy(
      masterCopy: null
    ): TypedEventFilter<[string], { masterCopy: string }>;
  };

  estimateGas: {
    NAME(overrides?: CallOverrides): Promise<BigNumber>;

    "NAME()"(overrides?: CallOverrides): Promise<BigNumber>;

    VERSION(overrides?: CallOverrides): Promise<BigNumber>;

    "VERSION()"(overrides?: CallOverrides): Promise<BigNumber>;

    /**
     * Allows to upgrade the contract. This can only be done via a Safe transaction.
     * @param _masterCopy New contract address.
     */
    changeMasterCopy(
      _masterCopy: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    /**
     * Allows to upgrade the contract. This can only be done via a Safe transaction.
     * @param _masterCopy New contract address.
     */
    "changeMasterCopy(address)"(
      _masterCopy: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    friends(arg0: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>;

    "friends(uint256)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    isConfirmed(
      arg0: BytesLike,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "isConfirmed(bytes32,address)"(
      arg0: BytesLike,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    isExecuted(arg0: BytesLike, overrides?: CallOverrides): Promise<BigNumber>;

    "isExecuted(bytes32)"(
      arg0: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    isFriend(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    "isFriend(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    manager(overrides?: CallOverrides): Promise<BigNumber>;

    "manager()"(overrides?: CallOverrides): Promise<BigNumber>;

    threshold(overrides?: CallOverrides): Promise<BigNumber>;

    "threshold()"(overrides?: CallOverrides): Promise<BigNumber>;

    /**
     * Setup function sets initial storage of contract.
     * @param _friends List of friends' addresses.
     * @param _threshold Required number of friends to confirm replacement.
     */
    setup(
      _friends: string[],
      _threshold: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    /**
     * Setup function sets initial storage of contract.
     * @param _friends List of friends' addresses.
     * @param _threshold Required number of friends to confirm replacement.
     */
    "setup(address[],uint256)"(
      _friends: string[],
      _threshold: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    /**
     * Allows a friend to confirm a Safe transaction.
     * @param dataHash Safe transaction hash.
     */
    confirmTransaction(
      dataHash: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    /**
     * Allows a friend to confirm a Safe transaction.
     * @param dataHash Safe transaction hash.
     */
    "confirmTransaction(bytes32)"(
      dataHash: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    /**
     * Returns if Safe transaction is a valid owner replacement transaction.
     * @param newOwner New owner address.
     * @param oldOwner Owner address to be replaced.
     * @param prevOwner Owner that pointed to the owner to be replaced in the linked list
     * @returns Returns if transaction can be executed.
     */
    recoverAccess(
      prevOwner: string,
      oldOwner: string,
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    /**
     * Returns if Safe transaction is a valid owner replacement transaction.
     * @param newOwner New owner address.
     * @param oldOwner Owner address to be replaced.
     * @param prevOwner Owner that pointed to the owner to be replaced in the linked list
     * @returns Returns if transaction can be executed.
     */
    "recoverAccess(address,address,address)"(
      prevOwner: string,
      oldOwner: string,
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    /**
     * Returns if Safe transaction is a valid owner replacement transaction.
     * @param dataHash Data hash.
     * @returns Confirmation status.
     */
    isConfirmedByRequiredFriends(
      dataHash: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    /**
     * Returns if Safe transaction is a valid owner replacement transaction.
     * @param dataHash Data hash.
     * @returns Confirmation status.
     */
    "isConfirmedByRequiredFriends(bytes32)"(
      dataHash: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    /**
     * Returns hash of data encoding owner replacement.
     * @param data Data payload.
     * @returns Data hash.
     */
    getDataHash(data: BytesLike, overrides?: CallOverrides): Promise<BigNumber>;

    /**
     * Returns hash of data encoding owner replacement.
     * @param data Data payload.
     * @returns Data hash.
     */
    "getDataHash(bytes)"(
      data: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    NAME(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "NAME()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    VERSION(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "VERSION()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    /**
     * Allows to upgrade the contract. This can only be done via a Safe transaction.
     * @param _masterCopy New contract address.
     */
    changeMasterCopy(
      _masterCopy: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    /**
     * Allows to upgrade the contract. This can only be done via a Safe transaction.
     * @param _masterCopy New contract address.
     */
    "changeMasterCopy(address)"(
      _masterCopy: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    friends(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "friends(uint256)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    isConfirmed(
      arg0: BytesLike,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "isConfirmed(bytes32,address)"(
      arg0: BytesLike,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    isExecuted(
      arg0: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "isExecuted(bytes32)"(
      arg0: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    isFriend(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "isFriend(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    manager(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "manager()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    threshold(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "threshold()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    /**
     * Setup function sets initial storage of contract.
     * @param _friends List of friends' addresses.
     * @param _threshold Required number of friends to confirm replacement.
     */
    setup(
      _friends: string[],
      _threshold: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    /**
     * Setup function sets initial storage of contract.
     * @param _friends List of friends' addresses.
     * @param _threshold Required number of friends to confirm replacement.
     */
    "setup(address[],uint256)"(
      _friends: string[],
      _threshold: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    /**
     * Allows a friend to confirm a Safe transaction.
     * @param dataHash Safe transaction hash.
     */
    confirmTransaction(
      dataHash: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    /**
     * Allows a friend to confirm a Safe transaction.
     * @param dataHash Safe transaction hash.
     */
    "confirmTransaction(bytes32)"(
      dataHash: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    /**
     * Returns if Safe transaction is a valid owner replacement transaction.
     * @param newOwner New owner address.
     * @param oldOwner Owner address to be replaced.
     * @param prevOwner Owner that pointed to the owner to be replaced in the linked list
     * @returns Returns if transaction can be executed.
     */
    recoverAccess(
      prevOwner: string,
      oldOwner: string,
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    /**
     * Returns if Safe transaction is a valid owner replacement transaction.
     * @param newOwner New owner address.
     * @param oldOwner Owner address to be replaced.
     * @param prevOwner Owner that pointed to the owner to be replaced in the linked list
     * @returns Returns if transaction can be executed.
     */
    "recoverAccess(address,address,address)"(
      prevOwner: string,
      oldOwner: string,
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    /**
     * Returns if Safe transaction is a valid owner replacement transaction.
     * @param dataHash Data hash.
     * @returns Confirmation status.
     */
    isConfirmedByRequiredFriends(
      dataHash: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    /**
     * Returns if Safe transaction is a valid owner replacement transaction.
     * @param dataHash Data hash.
     * @returns Confirmation status.
     */
    "isConfirmedByRequiredFriends(bytes32)"(
      dataHash: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    /**
     * Returns hash of data encoding owner replacement.
     * @param data Data payload.
     * @returns Data hash.
     */
    getDataHash(
      data: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    /**
     * Returns hash of data encoding owner replacement.
     * @param data Data payload.
     * @returns Data hash.
     */
    "getDataHash(bytes)"(
      data: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
