/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  Signer,
  BytesLike,
  Contract,
  ContractFactory,
  Overrides,
} from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";

import type { DelegateConstructorProxy } from "../DelegateConstructorProxy";

export class DelegateConstructorProxy__factory extends ContractFactory {
  constructor(signer?: Signer) {
    super(_abi, _bytecode, signer);
  }

  deploy(
    _masterCopy: string,
    initializer: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<DelegateConstructorProxy> {
    return super.deploy(
      _masterCopy,
      initializer,
      overrides || {}
    ) as Promise<DelegateConstructorProxy>;
  }
  getDeployTransaction(
    _masterCopy: string,
    initializer: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(
      _masterCopy,
      initializer,
      overrides || {}
    );
  }
  attach(address: string): DelegateConstructorProxy {
    return super.attach(address) as DelegateConstructorProxy;
  }
  connect(signer: Signer): DelegateConstructorProxy__factory {
    return super.connect(signer) as DelegateConstructorProxy__factory;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): DelegateConstructorProxy {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as DelegateConstructorProxy;
  }
}

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_masterCopy",
        type: "address",
      },
      {
        internalType: "bytes",
        name: "initializer",
        type: "bytes",
      },
    ],
    payable: false,
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    payable: true,
    stateMutability: "payable",
    type: "fallback",
  },
];

const _bytecode =
  "0x608060405234801561001057600080fd5b506040516102ea3803806102ea8339818101604052604081101561003357600080fd5b81019080805190602001909291908051604051939291908464010000000082111561005d57600080fd5b8382019150602082018581111561007357600080fd5b825186600182028301116401000000008211171561009057600080fd5b8083526020830192505050908051906020019080838360005b838110156100c45780820151818401526020810190506100a9565b50505050905090810190601f1680156100f15780820380516001836020036101000a031916815260200191505b5060405250505081600073ffffffffffffffffffffffffffffffffffffffff168173ffffffffffffffffffffffffffffffffffffffff16141561017f576040517f08c379a00000000000000000000000000000000000000000000000000000000081526004018080602001828103825260248152602001806102c66024913960400191505060405180910390fd5b806000806101000a81548173ffffffffffffffffffffffffffffffffffffffff021916908373ffffffffffffffffffffffffffffffffffffffff1602179055505060008151111561020c5773ffffffffffffffffffffffffffffffffffffffff60005416600080835160208501846127105a03f46040513d6000823e6000821415610208573d81fd5b5050505b505060aa8061021c6000396000f3fe608060405273ffffffffffffffffffffffffffffffffffffffff600054167fa619486e0000000000000000000000000000000000000000000000000000000060003514156050578060005260206000f35b3660008037600080366000845af43d6000803e60008114156070573d6000fd5b3d6000f3fea265627a7a72315820ce9144ef12bb0edf8e9694736ce0502e96be581b7253f9687974b7d5945d0e2f64736f6c63430005100032496e76616c6964206d617374657220636f707920616464726573732070726f7669646564";
