export const INTERFACE_MESSAGES = {
  ENV_INFO: 'ENV_INFO',
  ON_SAFE_INFO: 'ON_SAFE_INFO',
  TRANSACTION_CONFIRMED: 'TRANSACTION_CONFIRMED',
  TRANSACTION_REJECTED: 'TRANSACTION_REJECTED',
  RPC_CALL_RESPONSE: 'RPC_CALL_RESPONSE',
} as const;

export const SDK_MESSAGES = {
  SAFE_APP_SDK_INITIALIZED: 'SAFE_APP_SDK_INITIALIZED',
  SEND_TRANSACTIONS: 'SEND_TRANSACTIONS',
  RPC_CALL: 'RPC_CALL',
  SEND_TRANSACTIONS_V2: 'SEND_TRANSACTIONS_V2',
} as const;
