export const INTERFACE_MESSAGES = {
  ON_SAFE_INFO: 'ON_SAFE_INFO',
  TRANSACTION_CONFIRMED: 'TRANSACTION_CONFIRMED',
} as const;

export const SDK_MESSAGES = {
  SAFE_APP_SDK_INITIALIZED: 'SAFE_APP_SDK_INITIALIZED',
  SEND_TRANSACTIONS: 'SEND_TRANSACTIONS',
} as const;
