export const INTERFACE_MESSAGES = {
  ENV_INFO: 'ENV_INFO',
  ON_SAFE_INFO: 'ON_SAFE_INFO',
  TRANSACTION_CONFIRMED: 'TRANSACTION_CONFIRMED',
  TRANSACTION_REJECTED: 'TRANSACTION_REJECTED',
} as const;

export const SDK_MESSAGES = {
  SAFE_APP_SDK_INITIALIZED: 'SAFE_APP_SDK_INITIALIZED',
  SEND_TRANSACTIONS: 'SEND_TRANSACTIONS',
} as const;
