name: 'CLA Assistant'
on:
  issue_comment:
    types: [created]
  pull_request_target:
    types: [opened, closed, synchronize]

permissions: {}

jobs:
  CLAssistant:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      issues: write
    steps:
      - name: Checkout reusable workflows
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          repository: safe-global/github-reusable-workflows
          token: ${{ secrets.REUSABLE_WORKFLOWS_TOKEN }}
          path: reusable-workflows
          ref: c4fd58f9c721aca09b841c8035ce1d115ed5f3c3 # v2.4.18
      - name: 'CLA Assistant'
        uses: ./reusable-workflows/actions/cla
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          personal-access-token: ${{ secrets.CLA_ACCESS_TOKEN }}
          allowlist: germartinez,rmeissner,Uxio0,dasanra,luarx,DaniSomoza,katspaugh,yagopv,JagoFigueroa,bot*
