name: 'ESLint check'
on: [pull_request]

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0

      - name: Use Node.js 18
        uses: actions/setup-node@3235b876344d2a9aa001b8d1453c930bba69e610 # v3.9.1
        with:
          node-version: 18
          cache: yarn

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Run eslint
        run: yarn lint:check
